# Generated by Django 5.0.6 on 2024-07-04 16:25

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 5, 16, 25, 37, 970837, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('user_id', 'event_id'), name='unique_event_user'),
        ),
    ]
